import matplotlib.pyplot as plt
import numpy as np

data_set1 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_.01")
data_set2 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_00001")
data_set5 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_00002")
data_set4 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_00003")
data_set3 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_00004")


plt.figure(1)
plt.plot(data_set1[:,0], data_set1[:,2], label=".1")
plt.plot(data_set2[:,0], data_set2[:,2], label="1")
#plt.plot(data_set3[:,0], data_set3[:,2], label="2")
plt.plot(data_set4[:,0], data_set4[:,2], label="3")
plt.plot(data_set5[:,0], data_set5[:,2], label="4")
plt.xlabel('time [s]')
plt.ylabel('vy [m/s]')
plt.title('time vs vy')
plt.legend(loc='upper right')
plt.grid(True)

data_set1 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/xy_RK4_.01")
data_set2 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/xy_RK4_00001")
data_set5 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/xy_RK4_00002")
data_set4 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/xy_RK4_00003")
data_set3 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/xy_RK4_00004")

plt.figure(2)
plt.plot(data_set1[:,0], data_set1[:,2], label=".1")
plt.plot(data_set2[:,0], data_set2[:,2], label="1")
plt.plot(data_set3[:,0], data_set3[:,2], label="2")
plt.plot(data_set4[:,0], data_set4[:,2], label="3")
plt.plot(data_set5[:,0], data_set5[:,2], label="4")
plt.xlabel('time [s]')
plt.ylabel('y [m]')
plt.title('time vs y')
plt.legend(loc='upper right')
plt.grid(True)

data_set1 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_-1_90")
data_set2 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_-5_90")
data_set3 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_5_90")
data_set4 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_5_60")
data_set5 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_5_30")
data_set6 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/vxvy_RK4_20_160")

fig1, axs1 = plt.subplots(1,2)
#plt.figure(3)
axs1[0].plot(data_set1[:,0], data_set1[:,2], label="-1 at 90")
axs1[0].plot(data_set2[:,0], data_set2[:,2], label="-5 at 90")
axs1[0].plot(data_set3[:,0], data_set3[:,2], label="5 at 90")
axs1[0].plot(data_set4[:,0], data_set4[:,2], label="5 at 60")
axs1[0].plot(data_set5[:,0], data_set5[:,2], label="5 at 30")
axs1[0].plot(data_set6[:,0], data_set6[:,2], label="20 at 160")
axs1[0].set_xlabel('time [s]')
axs1[0].set_ylabel('vy [m/s]')
axs1[0].set_title('time vs vy')
axs1[0].legend(loc='upper right')
axs1[0].grid(True)

axs1[1].plot(data_set1[:,0], data_set1[:,1], label="-1 at 90")
axs1[1].plot(data_set2[:,0], data_set2[:,1], label="-5 at 90")
axs1[1].plot(data_set3[:,0], data_set3[:,1], label="5 at 90")
axs1[1].plot(data_set4[:,0], data_set4[:,1], label="5 at 60")
axs1[1].plot(data_set5[:,0], data_set5[:,1], label="5 at 30")
axs1[1].plot(data_set6[:,0], data_set6[:,1], label="5 at 160")
axs1[1].set_ylabel('vx [m/s]')
axs1[1].set_title('time vs vx')
axs1[1].legend(loc='upper right')
axs1[1].grid(True)

data_set1 = np.loadtxt("/Users/phihung/NumMethod/first/homework/hw_05/time_velocity")
plt.figure(4)
plt.plot(data_set1[:,1], data_set1[:,0])
plt.ylabel('time of flight [s]')
plt.xlabel('initial velocity at 90 degrees [m/s]')
plt.title('initial velocity at 90 degrees vs time of flight')
plt.legend(loc='lower right')
plt.grid(True)

plt.show()

