import matplotlib.pyplot as plt
import numpy as np

data_duff2 = np.loadtxt('/Users/phihung/NumMethod/first/homework/hw_06/duffing_beta_phase2.dat')
data_duff8 = np.loadtxt('/Users/phihung/NumMethod/first/homework/hw_06/duffing_beta_phase8.dat')
data_duff14 = np.loadtxt('/Users/phihung/NumMethod/first/homework/hw_06/duffing_beta_phase14.dat')

#plt.figure(1)
fig1, axs1 = plt.subplots(1,3)
#plt.figure(1)
axs1[0].plot(data_duff2[:,1], data_duff2[:,2], label="2")
axs1[0].set_xlabel(r'$x$ [m]')
axs1[0].set_ylabel(r'$v$ [m/s]')
axs1[0].set_title('Phase Diagram for Duffing')
axs1[0].legend(loc='lower right')
axs1[0].grid(True)
axs1[1].plot(data_duff8[:,1], data_duff8[:,2], label="8")
axs1[1].set_xlabel(r'$x$ [m]')
axs1[1].set_ylabel(r'$v$ [m/s]')
axs1[1].set_title('Phase Diagram for Duffing')
axs1[1].legend(loc='lower right')
axs1[1].grid(True)
axs1[2].plot(data_duff14[:,1], data_duff14[:,2], label="14")
axs1[2].set_xlabel(r'$x$ [m]')
axs1[2].set_ylabel(r'$v$ [m/s]')
axs1[2].set_title('Phase Diagram for Duffing')
axs1[2].legend(loc='lower right')
axs1[2].grid(True)

data_duff2 = np.loadtxt('/Users/phihung/NumMethod/first/homework/hw_06/duffing_FFT2.dat')
data_duff8 = np.loadtxt('/Users/phihung/NumMethod/first/homework/hw_06/duffing_FFT8.dat')
data_duff14 = np.loadtxt('/Users/phihung/NumMethod/first/homework/hw_06/duffing_FFT14.dat')

plt.figure(2)
plt.plot(data_duff2[:,0], np.log(data_duff2[:,1]), label="2")
plt.plot(data_duff8[:,0], np.log(data_duff8[:,1]), label="8")
plt.plot(data_duff14[:,0], np.log(data_duff14[:,1]), label="14")
plt.xlabel(r'$\omega$ [Hz]')
plt.ylabel(r'$\ln(\left|f(\omega)\right|)$')
plt.title('Fourier Fast Transform')
plt.legend(loc='lower right')
plt.grid(True)

plt.show()

